[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线更新版

;去广告：支持
;自动测速：支持
;微软分流：不支持
;苹果分流：不支持
;增强中国IP段：支持
;增强国外GFW：不支持

;设置规则标志位
ruleset=🛑 广告拦截,[]GEOSITE,category-ads-all
ruleset=🏠 私有网络,[]GEOSITE,private
ruleset=🏠 私有网络,[]GEOIP,private,no-resolve
ruleset=✨ Gemini,[]GEOSITE,google-gemini
ruleset=🤖 AI 服务,[]GEOSITE,openai
ruleset=🤖 AI 服务,[]GEOSITE,anthropic
ruleset=🤖 AI 服务,[]GEOSITE,category-ai-!cn
ruleset=🔒 国内服务,[]GEOSITE,geolocation-cn
ruleset=🔒 国内服务,[]GEOIP,cn,no-resolve
ruleset=📹 油管视频,[]GEOSITE,youtube
ruleset=☁️ 云服务,[]GEOSITE,cloudflare
ruleset=☁️ 云服务,[]GEOIP,cloudflare,no-resolve
ruleset=🔍 谷歌服务,[]GEOSITE,google
ruleset=🔍 谷歌服务,[]GEOIP,google,no-resolve
ruleset=📲 电报消息,[]GEOSITE,telegram
ruleset=📲 电报消息,[]GEOIP,telegram,no-resolve
ruleset=🐱 代码托管,[]GEOSITE,github
ruleset=🐱 代码托管,[]GEOSITE,gitlab
ruleset=Ⓜ️ 微软服务,[]GEOSITE,microsoft
ruleset=Ⓜ️ 微软服务,[]GEOSITE,onedrive
ruleset=🍏 苹果服务,[]GEOSITE,apple
ruleset=🍏 苹果服务,[]GEOSITE,icloud
ruleset=🐦 推特/X,[]GEOSITE,twitter
ruleset=🐦 推特/X,[]GEOIP,twitter,no-resolve
ruleset=📘 Meta 系,[]GEOSITE,facebook
ruleset=📘 Meta 系,[]GEOSITE,instagram
ruleset=📘 Meta 系,[]GEOSITE,whatsapp
ruleset=📘 Meta 系,[]GEOIP,facebook,no-resolve
ruleset=🎮 Steam,[]GEOSITE,steam
ruleset=🛠️ 开发工具,[]GEOSITE,docker
ruleset=🛠️ 开发工具,[]GEOSITE,npmjs
ruleset=🛠️ 开发工具,[]GEOSITE,jetbrains
ruleset=🌍 非中国,[]GEOSITE,geolocation-!cn
ruleset=🔒 国内服务,[]GEOSITE,cn
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🛑 广告拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🤖 AI 服务`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=✨ Gemini`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=🔍 谷歌服务`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=Ⓜ️ 微软服务`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=🍏 苹果服务`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=📲 电报消息`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=🐦 推特/X`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=📘 Meta 系`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=🎮 Steam`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=🐱 代码托管`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=☁️ 云服务`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=🛠️ 开发工具`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=🏠 私有网络`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🔒 国内服务`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🌍 非中国`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 自动选择`[]DIRECT`.*
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true

clash_rule_base=https://raw.githubusercontent.com/monifcat/diy-clash-tweak/mihomo/config/clash_basic.yaml

;luck
